### ISSUE TITLE
Dataset dimensions 

### ISSUE THREAD

**Issue by TGyAlDeen** [noboevbo/ehpi_action_recognition#4]
Thanks for making this great work available.
my question is how the transformation happened in the datasets.
The datasets (Jhmdb and use case) dimensions are m rows x 1440 columns.
in the paper its written 

> The encoded joints are assigned in a
fixed order in a 1 × n × 3 matrix, where n stands for the
number of joints. After the human pose for a frame has been
encoded into such a matrix, it is appended as last column
to a m × n × 3 matrix and replaces the first column of
this matrix if it already contains m frames.

I think i'm lost here, can you please explain it.

**Comment by denclade** [comment]
The dataset files contain m rows which equal to m EHPIs. Have a look at the dataset loader, that's the place where the transformation in the actual matrix for training is done (https://github.com/noboevbo/nobos_torch_lib/blob/master/nobos_torch_lib/datasets/action_recognition_datasets/ehpi_dataset.py).
