### ISSUE TITLE
Demo always label the action as 'wave'

### ISSUE THREAD

**Issue by muhammadfraz** [noboevbo/ehpi_action_recognition#5]
I tried the demo "run_ehpi.py" and everything got setup and run very easily, well done for that. However, the result on live footage were very inaccurate. I wonder if I am doing anything wrong or if the demo code works on any assumption that I am not taking in to account. 
The demo starts and even if the person is idle, the classifier labels it as 'wave' after a few seconds and keeps the label no matter how still the person remains. I've tried it multiple times with various distances from camera but every time the demo labels the person's action as 'wave' and then do not change. 
Can you comment or provide any guideline as this does not seems to be the intending behaviours?

**Comment by nhatuan84** [comment]
i faced the same problem. the result is bad.

**Comment by Israrulhaq190** [comment]
Correct, Results are too bad.

**Comment by denclade** [comment]
Ahh sorry, there was an error that caused data to be changed by the visualization. I forgot to push the fix to Github and didn't notice the issue here. Thanks for your hints, after the fix it should work.
