### ISSUE TITLE
only use one frame when inference with the web camera

### ISSUE THREAD

**Issue by YCyuchen** [noboevbo/ehpi_action_recognition#9]
Thanks for providing the pipeline for action recognition. 
I tried the script "run_ehpi.py" and took a look on the code. It seems the actionnet only use one frame to predict the action. While in your paper, there're 32 skeletons sequence being concatenated together to get the action result. Although there is a parameter called `buffer_size` in this scripts, it doesn't contribute to the serial frames' action recognition. 
I feel a little bit confused, is there anything I misunderstood?

**Comment by denclade** [comment]
The input for the action recognition part is in get_actions in https://github.com/noboevbo/ehpi_action_recognition/blob/master/ehpi_action_recognition/networks/action_recognition_nets/action_rec_net_ehpi.py (ehpi_img), it consists of the skeleton feature vecs from the last 32 frames. The buffer in run_ehpi is a leftover, and not used in the action recognition (see action_buffer in action_rec_net_ehpi).
